apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-sa
  annotations:
    serviceaccounts.openshift.io/scc: custom-scc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-sa-binding
subjects:
- kind: ServiceAccount
  name: mongo-sa
  namespace: pxbbq
roleRef:
  kind: PodSecurityPolicy
  name: custom-psp
  apiGroup: policy
