apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: custom-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny  # You can adjust this based on your requirements
seLinuxContext:
  type: RunAsAny
