apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: custom-scc-for-mongodb
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
runAsUser:
  type: MustRunAs
  uidRangeMin: 1000810000
  uidRangeMax: 1000810000
seLinuxContext:
  type: MustRunAs
