apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: allow-all-deployments
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
fsGroup:
  type: RunAsAny
groups:
- "*"
priority: null
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- "*"
volumes:
- "*"
